management:
  endpoints:
    web:
      exposure:
        include:
          - info

language: fr

spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: isa
    password: superPassword
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
