management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - flags
          - settings

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: isa
    password: secret2
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

app:
  name: Spring Boot App
  author: Wojtek
  instances: 1
  thread:
    batch: 50
    threads: 4
    name: importantThread
